"use strict";
let a = prompt("enter value for a");
let b = prompt("enter value for a");
let c = a + b;
let d = a - b;
let e = a * b;
let g = a / b;
let f = a % b;
console.log(c);
console.log(d);
console.log(e);
console.log(g);
console.log(f);
